name: Android library
on: [push, pull_request]
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
      - uses: gradle/actions/setup-gradle@v4
      - name: Test, lint and build Android library
        run: bash ./gradlew :rhythm:testDebugUnitTest :rhythm:lintRelease :rhythm:assembleRelease :rhythm:publishReleasePublicationToMavenLocal --no-daemon
